package eu.bbmri_eric.quality.agent.audit;

public enum AuditAction {
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT,
  PASSWORD_CHANGED,

  USER_CREATED,
  USER_UPDATED,
  USER_DELETED,

  SETTINGS_UPDATED,

  QUALITY_CHECK_CREATED,
  QUALITY_CHECK_UPDATED,
  QUALITY_CHECK_DELETED,
  QUALITY_CHECK_CATEGORY_CREATED,
  QUALITY_CHECK_CATEGORY_UPDATED,
  QUALITY_CHECK_CATEGORY_DELETED,

  REPORT_CREATED,
  REPORT_GENERATED,

  SERVER_REGISTERED,
  SERVER_REGISTRATION_FAILED,
  SERVER_CONFIGURATION_CHANGED,
  SERVER_REPORT_UPLOADED,
  SERVER_CONNECTION_STATUS_CHANGED,

  AGENT_STARTED,
  AGENT_STOPPED,

  /** Fallback for audit events whose type does not map to a known action. */
  OTHER,
}
